name: Coverage

on:
  push:
    tags-ignore:
      - '*'
    paths-ignore:
      - '**.md'
      - '.github/*'
    branches:
      - main

jobs:
  coverage:
    name: Sending test coverage to Code Climate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run test -- --coverage
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
          debug: true
