name: Lint and test

on:
  push:
    tags-ignore:
      - '*'
    paths-ignore:
      - '**.md'
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm ci
      - run: npm run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 15
      - run: npm ci
      - run: npm run test
  coverage:
    needs: [ test ]
	if: github.ref == 'refs/heads/main'
    name: Sending test coverage to Code Climate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm ci
      - uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run test -- --coverage
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
          debug: true
